Repository tiiuae/ghaf, pull requests merged in 2023-12, with the labels that each got.

#370 wifi-connector: Support nmcli interface
  overlays/custom-packages/wifi-connector/default.nix
  packages/wifi-connector/default.nix
  targets/lenovo-x1-carbon.nix
Labels: Tested on Orin AGX, Tested on Lenovo X1 Carbon, Tested on NUC

#397 systemd-boot-dtb: Fix 23.11 remote nixos-rebuild
  modules/boot/systemd-boot-dtb.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Orin AGX Cross, Tested on Orin NX Cross

#399 flake.lock update
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on Orin AGX Cross, Tested on Orin NX Cross

#412 Update flake.lock
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on Orin AGX Cross, Tested on Orin NX Cross

#413 Set static timezone of Dubai only for Lenovo X1 target
  modules/virtualization/microvm/appvm.nix
  modules/virtualization/microvm/guivm.nix
  modules/virtualization/microvm/netvm.nix
  targets/lenovo-x1-carbon.nix
Labels: Tested on Orin NX, Tested on NUC, Tested on Orin AGX Cross
