Repository tiiuae/ghaf, pull requests merged in 2024-03, with the labels that each got.

#495 Update jetpack-nixos in flake.lock
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#432 Add warning about aarch64-linux flash-script
  lib/mk-flash-script/default.nix
Labels: Tested on Orin AGX

#506 Initial minimal systemd for Ghaf
  modules/common/common.nix
  modules/common/default.nix
  modules/common/systemd/base.nix
  modules/common/systemd/default.nix
  modules/microvm/virtualization/microvm/appvm.nix
  modules/microvm/virtualization/microvm/guivm.nix
  modules/microvm/virtualization/microvm/microvm-host.nix
  modules/microvm/virtualization/microvm/netvm.nix
  targets/generic-x86_64/flake-module.nix
  targets/lenovo-x1-installer/flake-module.nix
  targets/nvidia-jetson-orin/flake-module.nix
  targets/vm/flake-module.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on RISC-V

#523 Add perf and unixbench to debug tools
  modules/common/development/debug-tools.nix
Labels: Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on RISC-V, Tested on Orin NX Cross
