Repository tiiuae/ghaf, pull requests merged in 2024-08, with the labels that each got.

#704 remove wifi-connector
  modules/common/services/wifi.nix
  overlays/custom-packages/default.nix
  packages/wifi-connector/default.nix
Labels: Tested on Lenovo X1 Carbon

#478 Introduce new disk partitioning scheme
  modules/common/systemd/hardened-configs/common/systemd-remount-fs.nix
  modules/disko/disko-ab-partitions.nix
  modules/disko/disko-zfs-postboot.nix
  modules/disko/flake-module.nix
  modules/hardware/x86_64-generic/x86_64-linux.nix
  targets/laptop/flake-module.nix
Labels: Tested on Lenovo X1 Carbon

#707 Lock the screen when Yubikey hardware is plugged out
  modules/common/services/yubikey.nix
  modules/desktop/graphics/labwc.config.nix
Labels: Tested on Lenovo X1 Carbon

#732 Disable the windows-vm launcher for MVP trial
  modules/common/services/desktop.nix
  modules/profiles/mvp-user-trial.nix
Labels: Needs Testing

#752 fix: ghaf-host rootfs out-of-space fails to boot
  modules/common/development/nix.nix
Labels: Needs Testing

#755 Increase AppFlowy-VM RAM to avoid crashing.
  modules/reference/appvms/appflowy.nix
Labels: Needs Testing

#751 Add ghafpkgs input and migrate some packages
  assets/ghaf-logo.png
  assets/icons/svg/admin-cog.svg
  assets/icons/svg/close.svg
  assets/icons/svg/ghaf-white.svg
  assets/icons/svg/icon_arrow.svg
  assets/icons/svg/iconify.svg
  assets/icons/svg/launchpad.svg
  assets/icons/svg/max.svg
  assets/icons/svg/wifi.svg
  assets/wallpaper.png
  flake.lock
  flake.nix
  modules/desktop/graphics/boot.nix
  modules/desktop/graphics/labwc.nix
  modules/desktop/graphics/waybar.config.nix
  modules/flake-module.nix
  modules/hardware/flake-module.nix
  overlays/custom-packages/default.nix
  packages/ghaf-openbox-theme/default.nix
  packages/ghaf-openbox-theme/themerc
Labels: Tested on Orin NX, Tested on Lenovo X1 Carbon

#765 Add a wiping option to the installer
  packages/installer/ghaf-installer.sh
Labels: Tested on Lenovo X1 Carbon

#686 Add support for USB hot plugging
  modules/hardware/common/default.nix
  modules/hardware/common/qemu.nix
  modules/hardware/common/usb/vhotplug.nix
  modules/microvm/virtualization/microvm/audiovm.nix
  modules/microvm/virtualization/microvm/netvm.nix
  modules/reference/profiles/laptop-x86.nix
  packages/qemuqmp/default.nix
  packages/vhotplug/default.nix
Labels: Tested on Lenovo X1 Carbon

#750 GIVC Implementation
  flake.lock
  flake.nix
  modules/common/development/debug-tools.nix
  modules/common/services/desktop.nix
  modules/flake-module.nix
  modules/givc/adminvm.nix
  modules/givc/appvm.nix
  modules/givc/audiovm.nix
  modules/givc/common.nix
  modules/givc/flake-module.nix
  modules/givc/guivm.nix
  modules/givc/host.nix
  modules/givc/netvm.nix
  modules/microvm/flake-module.nix
  modules/microvm/virtualization/microvm/adminvm.nix
  modules/microvm/virtualization/microvm/appvm.nix
  modules/microvm/virtualization/microvm/audiovm.nix
  modules/microvm/virtualization/microvm/common/storagevm.nix
  modules/microvm/virtualization/microvm/guivm.nix
  modules/microvm/virtualization/microvm/microvm-host.nix
  modules/microvm/virtualization/microvm/modules.nix
  modules/microvm/virtualization/microvm/netvm.nix
  modules/reference/appvms/appflowy.nix
  modules/reference/appvms/business.nix
  modules/reference/appvms/chromium.nix
  modules/reference/appvms/default.nix
  modules/reference/appvms/element.nix
  modules/reference/appvms/gala.nix
  modules/reference/appvms/zathura.nix
  modules/reference/profiles/laptop-x86.nix
  targets/laptop/flake-module.nix
Labels: Tested on Lenovo X1 Carbon

#724 Add comms-vm
  modules/common/networking/hosts.nix
  modules/common/services/desktop.nix
  modules/reference/appvms/comms.nix
  modules/reference/appvms/default.nix
  modules/reference/profiles/mvp-user-trial.nix
  modules/reference/services/dendrite-pinecone/dendrite-config.nix
  modules/reference/services/dendrite-pinecone/dendrite-pinecone.nix
  packages/icon-pack/default.nix
Labels: Tested on Lenovo X1 Carbon
