Repository tiiuae/ghaf, pull requests merged in 2024-04, with the labels that each got.

#534 Add screenshot tool Grim
  modules/desktop/graphics/labwc.nix
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#542 Fix icon IFD: Move the icon path existstance check to checkPhase
  modules/desktop/graphics/launchers.nix
Labels: Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V

#549 waybar: lock the wifi-signal-strength script
  packages/wifi-signal-strength/default.nix
Labels: Needs Testing

#553 Refactor USB network card patch a bit
  modules/common/hardware/ax88179_178a.nix
  modules/common/hardware/default.nix
  modules/common/hardware/usb-network-kernel-patch.nix
  targets/generic-x86_64/flake-module.nix
  targets/lenovo-x1-installer/flake-module.nix
  targets/lenovo-x1/everything.nix
Labels: Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V

#548 Fix generic-x86_64 build with labwc enabled
  modules/desktop/graphics/fonts.nix
  modules/desktop/graphics/waybar.config.nix
  targets/generic-x86_64/flake-module.nix
Labels: Tested on Lenovo X1 Carbon

#562 Bump all of the helper inputs
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin NX Cross

#448 Orin: UARTI passthrough to Net-VM
  docs/src/SUMMARY.md
  docs/src/technologies/device_tree_overlays_pt.md
  docs/src/technologies/nvidia_uarti_net_vm.md
  docs/src/technologies/passthrough.md
  modules/jetpack/nvidia-jetson-orin/jetson-orin.nix
  modules/jetpack/nvidia-jetson-orin/virtualization/default.nix
  modules/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/default.nix
  modules/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/patches/net_vm_dtb_with_uarti.patch
  modules/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/uarti_pt_host_overlay.dts
  targets/nvidia-jetson-orin/flake-module.nix
Labels: Tested on Orin AGX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#566 Move all ssh keys to single file
  modules/common/development/authorized_ssh_keys.nix
  modules/common/development/ssh.nix
  targets/lenovo-x1-installer/flake-module.nix
Labels: Tested on Lenovo X1 Carbon

#430 Add modified element-desktop application to appvm and make start icon on gui-vm
  assets/icons/png/element.png
  modules/common/hardware/lenovo-x1/definitions/default.nix
  overlays/custom-packages/default.nix
  overlays/custom-packages/element-desktop/default.nix
  overlays/custom-packages/element-desktop/element-main.patch
  overlays/custom-packages/element-gps/default.nix
  overlays/custom-packages/element-web/default.nix
  packages/element-gps/default.nix
  packages/element-gps/main.py
  packages/element-gps/setup.py
  packages/element-web/default.nix
  packages/element-web/matrix-react-sdk.patch
  packages/element-web/pin.nix
  targets/lenovo-x1/appvms/default.nix
  targets/lenovo-x1/appvms/element.nix
  targets/lenovo-x1/guivmExtraModules.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#572 Update other inputs than nixpkgs in flake.lock
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#567 Add Appflowy as an example of Flutter application.
  assets/icons/png/appflowy.png
  assets/icons/svg/appflowy.svg
  modules/desktop/graphics/demo-apps.nix
  targets/lenovo-x1/appvms/appflowy.nix
  targets/lenovo-x1/appvms/default.nix
  targets/lenovo-x1/everything.nix
  targets/lenovo-x1/guivmExtraModules.nix
Labels: Tested on Lenovo X1 Carbon
