Repository tiiuae/ghaf, pull requests merged in 2024-11, with the labels that each got.

#876 Desktop: Refactor audio and brightness controls
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/labwc.config.nix
  packages/audio-ctrl/default.nix
Labels: Tested on Lenovo X1 Carbon

#875 bump some tools
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#877 Add zoom web app in comms-vm
  modules/common/services/desktop.nix
  modules/reference/appvms/comms.nix
  modules/reference/appvms/default.nix
  packages/icon-pack/default.nix
Labels: Tested on Lenovo X1 Carbon

#882 Fix the camera pass through to the business-vm
  modules/hardware/common/usb/vhotplug.nix
Labels: Tested on Lenovo X1 Carbon

#867 desktop: add bar in targets without givc
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/labwc.nix
  modules/desktop/graphics/styles/launcher-style.nix
  modules/desktop/graphics/styles/lock-style.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#884 Add separate audio control channel
  modules/common/services/audio.nix
  modules/common/services/desktop.nix
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/labwc.config.nix
  packages/bt-launcher/default.nix
Labels: Tested on Lenovo X1 Carbon

#881 Change to use pulseaudio old tunnelin module
  modules/microvm/virtualization/microvm/common/ghaf-audio.nix
  overlays/custom-packages/default.nix
  overlays/custom-packages/pulseaudio/default.nix
  overlays/custom-packages/pulseaudio/pulseaudio-remove-dont-move.patch
Labels: Tested on Lenovo X1 Carbon

#883 networking: unbreak NixOS networking.hosts
  modules/common/networking/hosts.nix
Labels: Tested on Orin AGX, Tested on Lenovo X1 Carbon

#890 [Packages] Gala: update version
  packages/gala/default.nix
Labels: Tested on Lenovo X1 Carbon

#871 Adding google chrome program to ghaf
  modules/common/networking/hosts.nix
  modules/common/services/desktop.nix
  modules/desktop/graphics/demo-apps.nix
  modules/givc/common.nix
  modules/hardware/common/usb/vhotplug.nix
  modules/reference/appvms/business.nix
  modules/reference/appvms/comms.nix
  modules/reference/appvms/default.nix
  modules/reference/appvms/google-chrome.nix
  modules/reference/profiles/laptop-x86.nix
  modules/reference/profiles/mvp-user-trial.nix
  modules/reference/programs/default.nix
  modules/reference/programs/google-chrome.nix
  packages/ghaf-xdg-open/default.nix
  packages/icon-pack/default.nix
  packages/mitmweb-ui/default.nix
  packages/open-normal-extension/open_normal.sh
Labels: Tested on Lenovo X1 Carbon

#888 Desktop: BT system tray applet, global labwc options, desktop refactoring
  docs/src/ref_impl/creating_appvm.md
  modules/common/services/desktop.nix
  modules/desktop/graphics/demo-apps.nix
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/ghaf-launcher.nix
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/labwc.nix
  modules/desktop/graphics/launchers.nix
  modules/desktop/graphics/waybar.config.nix
  modules/desktop/profiles/graphics.nix
  modules/microvm/virtualization/microvm/guivm.nix
  modules/reference/programs/windows-launcher.nix
  overlays/custom-packages/default.nix
  packages/bt-launcher/default.nix
  packages/icon-pack/default.nix
  packages/nm-launcher/default.nix
Labels: documentation, Tested on Orin AGX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on VM

#886 desktop: fix text flash on login/logout
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/login-manager.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#897 Implement autoreconnect for hotplugged devices on VM restarts
  packages/vhotplug/default.nix
Labels: Tested on Lenovo X1 Carbon

#872 Integrate ctrl-panel with locale setting support
  flake.lock
  flake.nix
  modules/desktop/graphics/labwc.config.nix
Labels: Tested on Lenovo X1 Carbon

#902 Fix opening files from gui-vm
  packages/ghaf-xdg-open/default.nix
Labels: Tested on Lenovo X1 Carbon

#892 Generic initialize of audio devices
  modules/common/services/audio.nix
Labels: Tested on Lenovo X1 Carbon

#473 Wayland displaying using shared memory between virtual machines
  modules/common/systemd/hardened-configs/common/microvm@.nix
  modules/common/users/accounts.nix
  modules/desktop/graphics/ewwbar.nix
  modules/hardware/common/default.nix
  modules/hardware/common/shared-mem.nix
  modules/microvm/flake-module.nix
  modules/microvm/virtualization/microvm/common/waypipe.nix
  modules/microvm/virtualization/microvm/guivm.nix
  overlays/custom-packages/qemu/0001-ivshmem-flat-memory-support.patch
  overlays/custom-packages/qemu/default.nix
  packages/memsocket/default.nix
  packages/memsocket/module.nix
  packages/wifi-signal-strength/default.nix
Labels: Tested on Lenovo X1 Carbon

#899 Add dbus proxy via givc
  flake.lock
  flake.nix
  modules/common/services/bluetooth.nix
  modules/common/users/accounts.nix
  modules/givc/appvm.nix
  modules/givc/audiovm.nix
  modules/givc/guivm.nix
  modules/givc/host.nix
  modules/givc/netvm.nix
  modules/reference/personalize/authorizedSshKeys.nix
  packages/bt-launcher/default.nix
  packages/nm-launcher/default.nix
Labels: Tested on Lenovo X1 Carbon

#901 Desktop: Fix USB tray icon, add missing cursor types
  modules/common/services/disks.nix
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/labwc.nix
Labels: Tested on Lenovo X1 Carbon

#913 bump to fix the x11-extras building
  flake.lock
  flake.nix
Labels: Needs Testing

#910 Fix gui-vm not starting when no battery installed
  overlays/custom-packages/qemu/acpi-devices-passthrough-qemu-8.1.patch
Labels: Tested on Lenovo X1 Carbon

#905 Add camera related tools for test automation
  modules/common/development/debug-tools.nix
Labels: Needs Testing

#891 General Url fetcher script for ms and ghaf
  modules/reference/appvms/business.nix
  modules/reference/programs/google-chrome.nix
  modules/reference/services/proxy-server/3proxy-config.nix
  modules/reference/services/proxy-server/ms_url_fetcher.nix
  modules/reference/services/proxy-server/url_fetcher.nix
Labels: Tested on Lenovo X1 Carbon
