Repository tiiuae/ghaf, pull requests merged in 2024-01, with the labels that each got.

#415 fix: Failures reported by kernel-hardening-checker
  docs/src/architecture/hardening.md
  modules/host/ghaf_host_hardened_baseline
Labels: Tested on Orin AGX, Tested on Lenovo X1 Carbon

#433 Update .version to 24.03
  .version
Labels: Tested on NUC

#434 Orin AGX: Extract partitions while flashing
  modules/hardware/nvidia-jetson-orin/partition-template.nix
  modules/hardware/nvidia-jetson-orin/sdimage.nix
Labels: Tested on Orin AGX, Tested on Orin AGX Cross

#420 [Packages] Gala: update urls
  packages/gala/default.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#449 Conditionally enable systemd timesyncd patch
  overlays/custom-packages/systemd/default.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#426 Update flake.lock
  flake.lock
  flake.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#451 Fix waypipe in labwc
  modules/graphics/labwc.nix
  modules/graphics/weston.nix
  modules/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#452 Ensure string in systemd override check
  overlays/custom-packages/systemd/default.nix
Labels: Tested on NUC, Needs Testing
