Repository tiiuae/ghaf, pull requests merged in 2024-07, with the labels that each got.

#682 Bump flake.lock for ssh fixes
  flake.lock
  flake.nix
  modules/desktop/graphics/window-manager.nix
  modules/reference/appvms/appflowy.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on NUC, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#693 x1-installer: add checks in installer script, other improvements
  packages/installer/default.nix
  packages/installer/ghaf-installer.sh
  targets/lenovo-x1-installer/flake-module.nix
Labels: Tested on Lenovo X1 Carbon

#689 Enable Yubikey Authentication
  modules/common/services/default.nix
  modules/common/services/yubikey.nix
  modules/hardware/common/qemu.nix
  modules/hardware/lenovo-x1/definitions/x1-gen10.nix
  modules/hardware/lenovo-x1/definitions/x1-gen11.nix
  modules/microvm/virtualization/microvm/modules.nix
Labels: Tested on Lenovo X1 Carbon

#697 graphics: add ghaf-open command to launch applications
  modules/desktop/graphics/window-manager.nix
  packages/ghaf-open/default.nix
Labels: Tested on Orin AGX Cross, bug on Lenovo X1 Carbon

#700 logging: Update the logging server endpoint
  modules/microvm/virtualization/microvm/adminvm.nix
Labels: Tested on Lenovo X1 Carbon
