Repository tiiuae/ghaf, pull requests merged in 2024-09, with the labels that each got.

#768 [Lenovo X1] gui-vm: Enable GPU acceleration
  REUSE.toml
  modules/desktop/profiles/graphics.nix
  modules/hardware/lenovo-x1/definitions/x1-gen11.nix
  modules/microvm/virtualization/microvm/0001-x86-gpu-Don-t-reserve-stolen-memory-for-GPU-passthro.patch
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#758 Create testing profile for non-default features
  modules/microvm/virtualization/microvm/guivm.nix
  modules/reference/profiles/default.nix
  modules/reference/profiles/mvp-user-trial-extras.nix
  modules/reference/profiles/mvp-user-trial.nix
  targets/laptop/flake-module.nix
  targets/laptop/laptop-configuration-builder.nix
Labels: Tested on Lenovo X1 Carbon

#762 move all hardware related modules inside hardware folder
  REUSE.toml
  docs/src/technologies/device_tree_overlays_pt.md
  docs/src/technologies/nvidia_uarti_net_vm.md
  modules/flake-module.nix
  modules/hardware/flake-module.nix
  modules/reference/hardware/default.nix
  modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
  modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330.nix
  modules/reference/hardware/imx8/default.nix
  modules/reference/hardware/imx8/imx8mp-sdimage.nix
  modules/reference/hardware/jetpack-microvm/agx-netvm-wlan-pci-passthrough.nix
  modules/reference/hardware/jetpack-microvm/default.nix
  modules/reference/hardware/jetpack-microvm/nx-netvm-ethernet-pci-passthrough.nix
  modules/reference/hardware/jetpack-microvm/pci-passthrough-agx-test.patch
  modules/reference/hardware/jetpack-microvm/pci-passthrough-nx-test.patch
  modules/reference/hardware/jetpack/default.nix
  modules/reference/hardware/jetpack/ghaf_host_hardened_baseline-jetson-orin
  modules/reference/hardware/jetpack/nvidia-jetson-orin/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/edk2-nvidia-always-reset-display.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/format-module.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/jetson-orin.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/mk-esp-contents.py
  modules/reference/hardware/jetpack/nvidia-jetson-orin/optee.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/ota-utils-fix.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/partition-template.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/pci-passthrough-common.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/sdimage.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/tegra2-mb2-bct-scr.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/patches/0002-vfio_platform-reset-required-false.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/patches/0003-bpmp-support-bpmp-virt.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/patches/0004-bpmp-virt-drivers.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/patches/0005-bpmp-overlay.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/overlays/qemu/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/overlays/qemu/patches/0001-qemu-v8.1.3_bpmp-virt.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/patches/0001-bpmp-host-proxy-dts.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/patches/0002-bpmp-host-uarta-dts.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/uarta-host/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/default.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/patches/net_vm_dtb_with_uarti.patch
  modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/uarti_pt_host_overlay.dts
  modules/reference/hardware/jetpack/profiles/debug.nix
  modules/reference/hardware/jetpack/profiles/default.nix
  modules/reference/hardware/laptop.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
  modules/reference/hardware/lenovo-x1/kernel/guest/test/default.nix
  modules/reference/hardware/lenovo-x1/kernel/guest/test/test-configuration.nix
  modules/reference/hardware/polarfire/default.nix
  modules/reference/hardware/polarfire/mpfs-nixos-sdimage.nix
  targets/laptop/flake-module.nix
  targets/nvidia-jetson-orin/flake-module.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on RISC-V, Tested on Orin AGX Cross, Tested on Orin NX Cross

#775 Slack: make metadata persistent
  modules/reference/appvms/comms.nix
Labels: Tested on Lenovo X1 Carbon

#785 Fix pdfopener
  modules/reference/appvms/business.nix
  modules/reference/appvms/chromium.nix
  packages/openPdf/default.nix
Labels: Tested on Lenovo X1 Carbon

#787 Fix brightness on Lenovo X1 Carbon 21HM0072MX
  modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
Labels: Tested on Lenovo X1 Carbon

#781 desktop: Add descriptions for launcher applications
  modules/common/services/desktop.nix
  modules/desktop/graphics/demo-apps.nix
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/labwc.nix
  modules/desktop/graphics/launchers.nix
  modules/desktop/graphics/waybar.config.nix
  modules/desktop/profiles/graphics.nix
  modules/reference/programs/windows-launcher.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross

#774 gui-vm: Change kernel to linux latest and fix path issue
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/profiles/graphics.nix
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#780 Add test for the installer
  flake.nix
  packages/installer/default.nix
  packages/installer/ghaf-installer.sh
  tests/flake-module.nix
  tests/installer/default.nix
Labels: Tested on Lenovo X1 Carbon

#792 AGX nmcli for netvm
  modules/reference/hardware/jetpack-microvm/agx-netvm-wlan-pci-passthrough.nix
Labels: Tested on Orin AGX

#798 Add a calculator to the ui vm
  modules/common/services/desktop.nix
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Needs Testing

#799 Add a sticky notes application.
  modules/common/services/desktop.nix
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#789 OP-TEE: Add option for PKCS11 TA (CFG_PKCS11_TA_LOCK_PIN_AFTER_FAILED_LOGIN_ATTEMPTS)
  LICENSES/BSD-2-Clause.txt
  REUSE.toml
  modules/reference/hardware/jetpack/nvidia-jetson-orin/optee.nix
  targets/nvidia-jetson-orin/0001-ta-pkcs11-Build-time-option-for-controlling-pin-lock.patch
  targets/nvidia-jetson-orin/optee.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Orin AGX Cross, Tested on Orin NX Cross

#788 Add common Ghaf audio configuration for app-vms
  modules/common/services/audio.nix
  modules/microvm/virtualization/microvm/appvm.nix
  modules/microvm/virtualization/microvm/common/ghaf-audio.nix
  modules/reference/appvms/business.nix
  modules/reference/appvms/chromium.nix
  modules/reference/appvms/comms.nix
Labels: Tested on Lenovo X1 Carbon
