Repository tiiuae/ghaf, pull requests merged in 2025-02, with the labels that each got.

#990 bump microvm
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon

#983 Desktop: Add window send-to-desktop keybinds, refine EWW logging & error handling
  modules/desktop/graphics/ewwbar/config/scripts/default.nix
  modules/desktop/graphics/ewwbar/config/variables/default.nix
  modules/desktop/graphics/ewwbar/config/widgets/default.nix
  modules/desktop/graphics/ewwbar/config/windows/default.nix
  modules/desktop/graphics/labwc.config.nix
Labels: Tested on Lenovo X1 Carbon

#999 admin-vm: Add more filters in loki drop stage
  modules/common/logging/logs-aggregator.nix
Labels: Tested on Lenovo X1 Carbon

#1000 bump: standard bump
  flake.lock
  flake.nix
  modules/hardware/flake-module.nix
Labels: Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Needs Testing

#1001 Desktop: Fix taskbar reserving space on fullscreen events
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/ewwbar/config/scripts/default.nix
Labels: Tested on Lenovo X1 Carbon

#1007 Fix issue with (not) auto-selecting 3.5mm headphone jack
  modules/common/services/audio.nix
Labels: Tested on Lenovo X1 Carbon

#1010 bump: flake bump
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#941 Update XDG handlers to use GIVC instead of SSH
  flake.lock
  flake.nix
  modules/common/security/apparmor/profiles/google-chrome.nix
  modules/common/services/default.nix
  modules/common/services/xdghandlers.nix
  modules/common/services/xdgopener.nix
  modules/microvm/virtualization/microvm/appvm.nix
  modules/microvm/virtualization/microvm/common/xdghandlers.nix
  modules/microvm/virtualization/microvm/common/xdgitems.nix
  modules/microvm/virtualization/microvm/guivm.nix
  modules/microvm/virtualization/microvm/microvm-host.nix
  modules/microvm/virtualization/microvm/modules.nix
  modules/reference/appvms/business.nix
  modules/reference/appvms/chromium.nix
  modules/reference/appvms/comms.nix
  modules/reference/appvms/google-chrome.nix
  modules/reference/appvms/zathura.nix
Labels: Tested on Lenovo X1 Carbon

#1022 Desktop: Fix desktop services not starting after wlr-randr v0.5.0
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/labwc.config.nix
Labels: Tested on Lenovo X1 Carbon

#1024 bump: another standard bump
  flake.lock
  flake.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin NX Cross, bug on Orin AGX Cross

#1019 givc bump
  flake.lock
  flake.nix
  modules/givc/host.nix
  modules/microvm/virtualization/microvm/common/xdgitems.nix
  modules/microvm/virtualization/microvm/guivm.nix
  packages/open-normal-extension/open_normal.sh
Labels: Tested on Lenovo X1 Carbon

#1035 Docs: add ghaf-24.12.3 release notes
  docs/src/SUMMARY.md
  docs/src/release_notes/ghaf-24.12.3.md
  docs/src/release_notes/release_notes.md
Labels: release notes

#1037 Fix element-gps to work with newer websocket lib
  packages/element-gps/main.py
Labels: Tested on Lenovo X1 Carbon
