Repository tiiuae/ghaf, pull requests merged in 2025-01, with the labels that each got.

#937 Compress generic-x86_64 image
  targets/generic-x86_64/flake-module.nix
Labels: Tested on NUC

#939 Custom PAM rule for desktop login
  modules/common/users/admin.nix
  modules/common/users/desktop.nix
  modules/desktop/graphics/labwc.nix
  modules/microvm/virtualization/microvm/audiovm.nix
  modules/microvm/virtualization/microvm/guivm.nix
  modules/microvm/virtualization/microvm/microvm-host.nix
  modules/reference/services/ollama/ollama.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon

#943 Multiple errors on wrong password entry at lock screen
  REUSE.toml
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/styles/lock-layout.nix
  overlays/README.md
  overlays/custom-packages/default.nix
  overlays/custom-packages/gtklock/0001-Multiple-errors-on-wrong-password.patch
  overlays/custom-packages/gtklock/default.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon

#932 Desktop: eww config refactor, mic volume widget
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/ewwbar/config/scripts/default.nix
  modules/desktop/graphics/ewwbar/config/variables/default.nix
  modules/desktop/graphics/ewwbar/config/widgets/default.nix
  modules/desktop/graphics/ewwbar/config/windows/default.nix
  modules/desktop/graphics/labwc.nix
  modules/desktop/graphics/styles/ewwbar-style.nix
Labels: Tested on Lenovo X1 Carbon

#955 Desktop: Select audio device from taskbar
  modules/desktop/graphics/ewwbar/config/scripts/default.nix
  modules/desktop/graphics/ewwbar/config/variables/default.nix
  modules/desktop/graphics/ewwbar/config/widgets/default.nix
  modules/desktop/graphics/styles/ewwbar-style.nix
Labels: Tested on Lenovo X1 Carbon

#958 admin-vm: Add loki process to drop expressions
  modules/common/logging/logs-aggregator.nix
Labels: Tested on Lenovo X1 Carbon

#960 Desktop: Automatic scaling on HiDPI displays
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/ewwbar/config/scripts/default.nix
  modules/desktop/graphics/ewwbar/config/widgets/default.nix
  modules/desktop/graphics/ewwbar/config/windows/default.nix
  modules/desktop/graphics/labwc.config.nix
  modules/desktop/graphics/styles/ewwbar-style.nix
Labels: Tested on Lenovo X1 Carbon

#956 Enable systemd hardened configs in gui-vm
  modules/common/systemd/hardened-configs/common/systemd-udevd.nix
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#930 Disable nix tooling
  modules/common/development/nix.nix
  modules/microvm/virtualization/microvm/microvm-host.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon

#984 fix: correct ownership of proxy service files
  modules/reference/services/pac/pac.nix
  modules/reference/services/proxy-server/3proxy-config.nix
Labels: Tested on Lenovo X1 Carbon

#974 Chromecast support
  flake.lock
  flake.nix
  modules/microvm/virtualization/microvm/netvm.nix
  modules/reference/appvms/google-chrome.nix
  modules/reference/profiles/mvp-user-trial.nix
  modules/reference/services/chromecast/chromecast-config.nix
  modules/reference/services/chromecast/chromecast.nix
  modules/reference/services/default.nix
  modules/reference/services/dendrite-pinecone/dendrite-pinecone.nix
  modules/reference/services/nw-packet-forwarder/nw-packet-forwarder.nix
  modules/reference/services/smcroute/smcroute.nix
Labels: Tested on Lenovo X1 Carbon
