Repository tiiuae/ghaf, pull requests merged in 2025-09, with the labels that each got.

#1319 ARP protection
  modules/common/common.nix
  modules/common/firewall/firewall.nix
  modules/common/firewall/kernel-modules.nix
  modules/common/services/wifi.nix
  modules/microvm/common/vm-networking.nix
  modules/microvm/host/networking.nix
  modules/microvm/sysvms/idsvm/mitmproxy/default.nix
  modules/reference/services/chromecast/chromecast-config.nix
  modules/reference/services/dendrite-pinecone/dendrite-config.nix
Labels: Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross

#1339 enable graphical boot, bump ghafpkgs, adjust cosmic config
  flake.lock
  modules/desktop/graphics/boot.nix
  modules/desktop/graphics/cosmic/config/cosmic-config.nix
  modules/microvm/host/microvm-host.nix
  modules/reference/profiles/mvp-orinuser-trial-extras.nix
  modules/reference/profiles/mvp-orinuser-trial.nix
  modules/reference/profiles/mvp-user-trial.nix
  overlays/custom-packages/cosmic/cosmic-osd/default.nix
  overlays/custom-packages/default.nix
Labels: Tested on Lenovo X1 Carbon

#1344 audit: add Nix-specific rules
  modules/common/security/audit/default.nix
  modules/common/security/audit/rules/common.nix
  modules/common/security/audit/rules/host.nix
  modules/reference/appvms/zathura.nix
  modules/reference/personalize/authorizedSshKeys.nix
Labels: Tested on Lenovo X1 Carbon

#1406 feat(boot): enable graphical boot on guivm, fix darp11 graphical boot
  modules/desktop/graphics/boot.nix
  modules/microvm/host/microvm-host.nix
  modules/microvm/sysvms/guivm.nix
  modules/reference/hardware/system76/definitions/system76-darp11-b.nix
Labels: Tested on Lenovo X1 Carbon, Tested on System76

#1389 Update vhotplug to support new config format and external API
  flake.lock
  flake.nix
  modules/hardware/common/usb/vhotplug.nix
  modules/reference/hardware/jetpack/nvidia-jetson-orin/jetson-orin.nix
Labels: Tested on Lenovo X1 Carbon, Tested on System76

#1407 Enabling fail2ban module
  modules/common/firewall/attack-mitigation.nix
  modules/common/firewall/default.nix
  modules/common/firewall/firewall.nix
  modules/common/security/default.nix
  modules/common/security/fail2ban.nix
  modules/common/security/ssh-tarpit/default.nix
  modules/development/ssh.nix
  modules/microvm/appvm.nix
  modules/microvm/sysvms/adminvm.nix
  modules/microvm/sysvms/audiovm.nix
  modules/microvm/sysvms/guivm.nix
  modules/microvm/sysvms/netvm.nix
  tests/firewall/default.nix
Labels: Tested on Orin AGX, Tested on System76

#1418 Fix ctrl-panel VM starting
  flake.lock
Labels: Tested on Lenovo X1 Carbon

#1433 Add tls_config support to alloy server
  modules/common/logging/server.nix
  modules/microvm/sysvms/adminvm.nix
Labels: Tested on System76
