Repository tiiuae/ghaf, pull requests merged in 2025-03, with the labels that each got.

#1044 Desktop: Kill user processes on logout
  modules/desktop/graphics/ewwbar/config/widgets/default.nix
  modules/desktop/graphics/labwc.config.nix
  packages/ghaf-powercontrol/default.nix
Labels: Tested on Lenovo X1 Carbon

#1040 Desktop: Persistent display config for each user session
  modules/desktop/graphics/ewwbar.nix
  modules/desktop/graphics/ewwbar/config/scripts/default.nix
  modules/desktop/graphics/labwc.config.nix
Labels: Tested on Lenovo X1 Carbon

#926 Ctrl panel bug report
  flake.lock
  flake.nix
  modules/common/logging/hw-mac-retrieve.nix
  modules/common/services/default.nix
  modules/common/services/github.nix
  modules/microvm/virtualization/microvm/guivm.nix
Labels: Tested on Lenovo X1 Carbon

#1045 Fix: mitmweb-ui
  flake.lock
  modules/microvm/virtualization/microvm/guivm.nix
  modules/microvm/virtualization/microvm/idsvm/mitmproxy/default.nix
  modules/reference/appvms/google-chrome.nix
  packages/own-pkgs-overlay.nix
  packages/pkgs-by-name/mitmweb-ui/package.nix
Labels: Tested on Lenovo X1 Carbon

#1005 disko: use ext4 and btrfs for debug builds
  modules/common/users/desktop.nix
  modules/disko/disko-ab-partitions.nix
  modules/disko/disko-basic-partition-v1.nix
  modules/disko/disko-basic-postboot.nix
  modules/disko/disko-debug-partition.nix
  modules/disko/disko-postboot.nix
  modules/disko/disko-zfs-postboot.nix
  modules/disko/flake-module.nix
  modules/givc/host.nix
  modules/hardware/x86_64-generic/x86_64-linux.nix
  modules/microvm/virtualization/microvm/common/shared-directory.nix
  modules/microvm/virtualization/microvm/common/storagevm.nix
  modules/microvm/virtualization/microvm/common/xdgitems.nix
  modules/microvm/virtualization/microvm/microvm-host.nix
  packages/flake-module.nix
  targets/laptop/flake-module.nix
  tests/installer/default.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon

#1041 Fix file manager refresh issue
  modules/microvm/virtualization/microvm/microvm-host.nix
  overlays/custom-packages/default.nix
  overlays/custom-packages/libfm/default.nix
  overlays/custom-packages/libfm/libfm-folder-reload.patch
  packages/vinotify/default.nix
  packages/vinotify/vinotify/requirements.txt
  packages/vinotify/vinotify/setup.py
  packages/vinotify/vinotify/vinotify/__init__.py
  packages/vinotify/vinotify/vinotify/vinotify.py
Labels: Tested on Lenovo X1 Carbon

#945 Add ballooning monitor for VMs
  modules/microvm/appvm.nix
  modules/microvm/flake-module.nix
  modules/microvm/mem-manager.nix
  targets/laptop/laptop-configuration-builder.nix
Labels: Tested on Lenovo X1 Carbon

#1061 dell-7330: Add new network controller PCI device
  modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330.nix
Labels: Needs Testing

#1065 Release note 24.12.4
  docs/src/SUMMARY.md
  docs/src/release_notes/ghaf-24.12.4.md
  docs/src/release_notes/release_notes.md
Labels: release notes

#1062 Refactor appvm module
  flake.lock
  modules/microvm/appvm.nix
  modules/microvm/sysvms/guivm.nix
  modules/profiles/laptop-x86.nix
  modules/reference/appvms/business.nix
  modules/reference/appvms/chromium.nix
  modules/reference/appvms/comms.nix
  modules/reference/appvms/default.nix
  modules/reference/appvms/gala.nix
  modules/reference/appvms/google-chrome.nix
  modules/reference/appvms/zathura.nix
  modules/reference/profiles/mvp-user-trial.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1070 bump: nw-packet-forwarder
  flake.lock
  modules/reference/services/nw-packet-forwarder/nw-packet-forwarder.nix
Labels: Tested on Lenovo X1 Carbon

#1091 bump: all the assistant packages
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1111 docs:add release note 25.03
  docs/src/SUMMARY.md
  docs/src/release_notes/ghaf-25.03.md
  docs/src/release_notes/release_notes.md
Labels: release notes
