Repository tiiuae/ghaf, pull requests merged in 2025-04, with the labels that each got.

#1115 Orin NX/AGX: Switch from nvidia bsp 5.15 kernel to upstream 6.6
  flake.lock
  modules/reference/hardware/jetpack/0001-ARM-SMMU-drivers-return-always-true-for-IOMMU_CAP_CA.patch
  modules/reference/hardware/jetpack/agx-netvm-wlan-pci-passthrough.nix
  modules/reference/hardware/jetpack/nx-netvm-ethernet-pci-passthrough.nix
  targets/nvidia-jetson-orin/flake-module.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1120 UI Idle management
  modules/desktop/graphics/ewwbar.nix
  modules/microvm/modules.nix
  modules/microvm/sysvms/guivm.nix
  modules/profiles/graphics.nix
  packages/ghaf-powercontrol/package.nix
  targets/laptop/flake-module.nix
Labels: Tested on Lenovo X1 Carbon

#1121 Bug fix SSRCSP-5890
  modules/common/systemd/hardened-configs/greetd.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1125 feat: power manager module, refactor ghaf-powercontrol
  modules/desktop/graphics/default.nix
  modules/desktop/graphics/power-manager.nix
  packages/ghaf-powercontrol/package.nix
  targets/nvidia-jetson-orin/flake-module.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1143 docs: Update Chapter 7. CI/CD in github.io pages
  docs/src/img/CICD_general.drawio.png
  docs/src/scs/ci-cd-system.md
Labels: documentation

#1149 Update vhotplug to fix issues with multiple devices with the same VID/PID
  overlays/custom-packages/qemu/default.nix
  overlays/custom-packages/qemu/usb-host-enable-autoscan-for-bus-addr.patch
  packages/python-packages/vhotplug/package.nix
Labels: Tested on Lenovo X1 Carbon

#1150 bump: standard bump
  flake.lock
  overlays/custom-packages/qemu/usb-host-enable-autoscan-for-bus-addr.patch
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1154 bugfix: fix Falcon AI app not starting, rework package
  modules/reference/desktop/applications.nix
  modules/reference/services/ollama/ollama.nix
  overlays/custom-packages/alpaca/default.nix
  overlays/custom-packages/default.nix
  packages/own-pkgs-overlay.nix
  packages/pkgs-by-name/falcon-launcher/package.nix
Labels: Tested on Lenovo X1 Carbon

#1171 refactor(desktop): remove sticky notes from cosmic, switch to oculante img viewer
  modules/microvm/common/xdghandlers.nix
  modules/microvm/common/xdgitems.nix
  modules/reference/desktop/applications.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1180 bugfix: cleanup display tmp files on logout
  modules/desktop/graphics/labwc.config.nix
  packages/ghaf-powercontrol/package.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross
