Repository tiiuae/ghaf, pull requests merged in 2025-08, with the labels that each got.

#1285 Basic firewall rules & testing
  .gitignore
  modules/common/firewall/default.nix
  modules/common/firewall/firewall.nix
  modules/common/firewall/kernel-modules.nix
  modules/common/logging/server.nix
  modules/common/services/audio.nix
  modules/microvm/common/vm-networking.nix
  modules/microvm/host/networking.nix
  modules/microvm/sysvms/idsvm/mitmproxy/default.nix
  modules/microvm/sysvms/netvm.nix
  modules/profiles/debug.nix
  modules/reference/appvms/business.nix
  modules/reference/appvms/google-chrome.nix
  modules/reference/programs/element-desktop.nix
  modules/reference/programs/windows-launcher.nix
  modules/reference/services/chromecast/chromecast.nix
  modules/reference/services/dendrite-pinecone/dendrite-pinecone.nix
  modules/reference/services/firewall/firewall.nix
  modules/reference/services/proxy-server/3proxy-config.nix
  modules/reference/services/smcroute/smcroute.nix
  targets/nvidia-jetson-orin/orin-configuration-builder.nix
  tests/firewall/default.nix
  tests/firewall/test_scripts/basic_rules.nix
  tests/flake-module.nix
Labels: Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1302 Changes to the VM target
  modules/givc/guivm.nix
  modules/microvm/appvm.nix
  modules/microvm/modules.nix
  targets/vm/flake-module.nix
Labels: Tested on VM

#1304 display: Drop x-igd-opregion device arg
  modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
  modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-2-in-1-gen-9.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-gen12.nix
  modules/reference/hardware/lenovo-x1/definitions/x1-gen13.nix
Labels: Tested on Lenovo X1 Carbon, Tested on rugged laptop

#1311 Setup normal exit for setup-ghaf-user service
  modules/common/users/desktop.nix
Labels: Tested on Lenovo X1 Carbon

#1264 feat(cosmic): propagate locale changes
  modules/common/common.nix
  modules/common/services/default.nix
  modules/common/services/locale.nix
  modules/microvm/sysvms/guivm.nix
Labels: documentation, Tested on Lenovo X1 Carbon

#1335 bugfix: add temporary watchdog service for high-CPU processes
  modules/desktop/graphics/cosmic/config/cosmic-config.nix
  modules/desktop/graphics/cosmic/default.nix
Labels: Tested on Lenovo X1 Carbon
