Repository tiiuae/ghaf, pull requests merged in 2025-05, with the labels that each got.

#1190 fix(desktop): adjust ghaf-launcher env vars
  modules/desktop/graphics/labwc.config.nix
Labels: Tested on Orin NX, Tested on Lenovo X1 Carbon

#1185 bump ghaf-givc
  flake.lock
  modules/givc/host.nix
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Lenovo X1 Carbon, Tested on Orin AGX Cross

#1193 Add security context indicator to COSMIC
  modules/desktop/graphics/cosmic/config/cosmic-config.nix
  modules/desktop/graphics/cosmic/default.nix
  modules/microvm/sysvms/guivm.nix
  overlays/custom-packages/cosmic/cosmic-comp/0001-Add-security-context-indicator.patch
  overlays/custom-packages/cosmic/cosmic-comp/default.nix
  overlays/custom-packages/default.nix
Labels: Tested on Lenovo X1 Carbon

#1192 bump:wireguard reactivating buttons and improvements
  flake.lock
  flake.nix
  modules/reference/services/wireguard-gui/wireguard-gui.nix
Labels: Tested on Lenovo X1 Carbon

#1191 bump: jetpack-nixos
  flake.lock
Labels: Tested on Orin AGX, Tested on Orin NX, Tested on Orin AGX Cross, Tested on Orin NX Cross

#1206 fix: Include the latest version of sticky-notes
  flake.lock
Labels: Tested on Lenovo X1 Carbon

#1213 vhotplug: Set precedence of ChromeVM over AudioVM
  modules/hardware/common/usb/vhotplug.nix
Labels: Tested on Lenovo X1 Carbon
